"""Evolui Post com categoria, snippet e Livros

Revision ID: 8a7e6d79dc35
Revises: 
Create Date: 2026-01-15 03:36:24.338156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7e6d79dc35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('codigo_snippet', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('livro_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_livro_id', 'livro', ['livro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_livro_id', type_='foreignkey')
        batch_op.drop_column('livro_id')
        batch_op.drop_column('codigo_snippet')
        batch_op.drop_column('categoria')

    op.drop_table('livro')
    # ### end Alembic commands ###
